#!/usr/bin/env node
/* Checks session.js by driving it the way the watch does and decoding what
 * comes back off the wire.
 *
 * The assertions are made against the reassembled AppMessage payload rather
 * than against session.js's internals, so this covers the frame format,
 * chunking and row-index alignment as well as the navigation. Row indices are
 * the part most worth pinning down: the watch says "row 7 was pressed" and
 * nothing else, so if the rows it drew and the targets this module kept ever
 * disagree, a press quietly does the wrong thing rather than failing.
 *
 * session.js is a thin coordinator over nav.js (navigation, frame assembly,
 * idle refresh) and actions.js (Siren action field-filling, confirmation,
 * retry) -- see the module comment at the top of session.js. This file is
 * what exercises the three wired together, end to end, exactly as index.js
 * drives them; tools/test-nav.js and tools/test-actions.js exercise nav.js
 * and actions.js directly, in isolation from each other, including the cases
 * (e.g. the idle-refresh/pending-action hook) that only make sense to check
 * against one module at a time.
 *
 * Run with: just test
 */

'use strict';

var path = require('path');
var Module = require('module');

/* --- the runtime PebbleKit JS provides and node does not ----------------- */

/* message_keys is generated by the Pebble build from package.json. The values
 * do not matter here; only that appmessage.js can look them up. */
var MESSAGE_KEYS = {
  CMD: 1, IDX: 2, ANSWER: 3, ANSWER_TEXT: 4, INBOX: 5, SEQ: 6,
  CHUNK_IDX: 7, CHUNK_N: 8, PAYLOAD: 9, STATE: 10, PROMPT_KIND: 11, LIVE: 12,
  ROOT: 13
};

var realResolve = Module._resolveFilename;
Module._resolveFilename = function (request) {
  if (request === 'message_keys') {
    return 'message_keys';
  }
  return realResolve.apply(this, arguments);
};
require.cache['message_keys'] = {
  id: 'message_keys', filename: 'message_keys', loaded: true,
  exports: MESSAGE_KEYS
};

/* A clock the tests drive by hand. Polling is a state machine over time, and
 * the only way to test it deterministically is to own the time. */
var now = 1000000;
var timers = [];
var nextTimerId = 1;

global.setTimeout = function (fn, ms) {
  var id = nextTimerId++;
  timers.push({ id: id, at: now + (ms || 0), fn: fn });
  return id;
};
global.clearTimeout = function (id) {
  for (var i = 0; i < timers.length; i++) {
    if (timers[i].id === id) {
      timers.splice(i, 1);
      return;
    }
  }
};
Date.now = function () { return now; };

/* tick advances the clock and runs whatever came due, oldest first. */
function tick(ms) {
  var until = now + ms;
  for (;;) {
    var next = null;
    for (var i = 0; i < timers.length; i++) {
      if (timers[i].at <= until && (!next || timers[i].at < next.at)) {
        next = timers[i];
      }
    }
    if (!next) {
      break;
    }
    now = next.at;
    global.clearTimeout(next.id);
    next.fn();
  }
  now = until;
}

var storage = {};
global.localStorage = {
  getItem: function (key) {
    return Object.prototype.hasOwnProperty.call(storage, key) ? storage[key] : null;
  },
  setItem: function (key, value) { storage[key] = String(value); },
  removeItem: function (key) { delete storage[key]; }
};

/* Frames the watch would have received, as raw AppMessage dictionaries. */
var sent = [];
global.Pebble = {
  sendAppMessage: function (message, onSuccess) {
    sent.push(message);
    onSuccess();
  }
};

/* --- a routed stub XHR --------------------------------------------------- */

var routes = {};
var requested = [];

function FakeXHR() {
  this.readyState = 0;
  this.status = 0;
  this.responseText = '';
  this.timeout = 0;
}
FakeXHR.prototype.open = function (method, url) {
  this.method = method;
  this.url = url;
};
FakeXHR.prototype.setRequestHeader = function () {};
FakeXHR.prototype.getAllResponseHeaders = function () { return ''; };
var sentBodies = [];

function respondFromRoutes(body) {
  requested.push(this.method + ' ' + this.url);
  sentBodies.push(body);
  var route = routes[this.method + ' ' + this.url] || routes[this.url];
  this.status = route ? (route.status || 200) : 404;
  this.responseText = route
    ? JSON.stringify(route.body)
    : '{"properties":{"message":"no such thing here"}}';
  this.readyState = 4;
  this.onreadystatechange();
}
FakeXHR.prototype.send = respondFromRoutes;
global.XMLHttpRequest = FakeXHR;

/* The modules under test log a running commentary. It is useful in the
 * emulator and noise here, so it goes to a sink and the assertions below print
 * through the real console. */
var realLog = console.log;
console.log = function () {};

var settings = require(path.join(__dirname, '..', 'src', 'pkjs', 'settings'));
var session = require(path.join(__dirname, '..', 'src', 'pkjs', 'session'));

/* --- decoding what the watch would have received ------------------------- */

var FIELD_SEP = '\x1f';

/* frames reassembles the chunk stream back into whole frames, exactly as
 * comm.c does: a chunk with index 0 starts a new one. */
function frames() {
  var out = [];
  var buffer = '';
  for (var i = 0; i < sent.length; i++) {
    var message = sent[i];
    if (message[MESSAGE_KEYS.CHUNK_IDX] === 0) {
      buffer = '';
    }
    buffer += message[MESSAGE_KEYS.PAYLOAD];
    if (message[MESSAGE_KEYS.CHUNK_IDX] ===
        message[MESSAGE_KEYS.CHUNK_N] - 1) {
      var parts = buffer.split(FIELD_SEP);
      out.push({
        title: parts[0],
        rows: parts[1] ? parts[1].split('\n') : [],
        kinds: parts[2] || '',
        message: parts[3] || '',
        heading: parts[4] || '',
        prompt: parts[5] || '',
        state: message[MESSAGE_KEYS.STATE],
        overlay: message[MESSAGE_KEYS.PROMPT_KIND],
        atRoot: message[MESSAGE_KEYS.ROOT],
        seq: message[MESSAGE_KEYS.SEQ]
      });
    }
  }
  return out;
}

function lastFrame() {
  var all = frames();
  return all[all.length - 1];
}

function reset() {
  sent = [];
  requested = [];
  sentBodies = [];
}

/* labels strips the sublabels, so a test can name a row without repeating its
 * whole rendering. */
function labels(frame) {
  var out = [];
  for (var i = 0; i < frame.rows.length; i++) {
    out.push(frame.rows[i].split('\t')[0]);
  }
  return out;
}

function indexOfRow(frame, label) {
  return labels(frame).indexOf(label);
}

/* --- the fixture API ----------------------------------------------------- */

var ROOT = {
  class: ['pantry'], title: 'The pantry',
  properties: { apiVersion: 1, kettle: 'cold' },
  entities: [{ class: ['shelf'], title: 'Top shelf',
               properties: { name: 'top', jars: 4 } }],
  links: [{ rel: ['self'], href: '/' }, { rel: ['shelves'], href: '/shelves' },
          /* The rel live mode matches against a job entity's class. */
          { rel: ['kettle-job'], href: '/job' }],
  actions: [
    { name: 'brew', title: 'Brew a pot of tea', method: 'POST',
      href: '/brew', fields: [] },
    { name: 'cool', title: 'Let the kettle cool', method: 'POST', href: '/cool',
      fields: [{ name: 'confirm', type: 'checkbox', required: true,
                 title: 'The kettle is still hot. Cool it anyway?' }] },
    { name: 'peek', title: 'Look inside', href: '/peek' }
  ]
};

var SHELVES = {
  class: ['shelf-list'], title: 'Shelves',
  properties: { count: 1 },
  links: [{ rel: ['self'], href: '/shelves' }]
};

var BASE = 'http://pantry.example/';

function setUp() {
  routes = {};
  routes[BASE] = { body: ROOT };
  routes[BASE + 'shelves'] = { body: SHELVES };
  routes['POST ' + BASE + 'brew'] = { status: 200,
    body: { properties: { state: 'done', id: 7 } } };
  routes['POST ' + BASE + 'cool'] = { body: { properties: { state: 'done' } } };
  routes['GET ' + BASE + 'peek'] = { body: { properties: { seen: true } } };
  settings.save([
    { name: 'pantry', baseUrl: BASE, secret: 'open-sesame' },
    { name: 'other', baseUrl: 'http://other.example/', secret: 'x' }
  ]);
  reset();
}

var failures = 0;

function assert(label, condition) {
  realLog((condition ? 'ok   ' : 'FAIL ') + label);
  if (!condition) { failures++; }
}

/* --- the tests ----------------------------------------------------------- */

function testPicker() {
  setUp();
  session.listBackends();
  var frame = lastFrame();
  assert('the picker lists every backend', frame.rows.length === 2);
  assert('the picker rows are backend rows', frame.kinds === 'bb');
  assert('the picker asks for nothing over HTTP', requested.length === 0);

  storage = {};
  reset();
  session.listBackends();
  frame = lastFrame();
  /* Not an empty list: an empty menu is what a backend with nothing in it
   * would look like, and this is not that. */
  assert('no backends is needs-config, not an empty list', frame.state === 4);
  assert('no backends says what to do', frame.message === 'No backends');
}

function testOpenAndRender() {
  setUp();
  session.listBackends();
  reset();
  session.activate(0);

  assert('opening a backend fetches its base URL',
         requested[0] === 'GET ' + BASE);
  var frame = lastFrame();
  assert('the document title comes from the server',
         frame.title === 'The pantry');
  /* Two properties, one embedded entity, three links, three actions. */
  assert('the document renders in Siren order', frame.kinds === 'ppelllaaa');
  assert('a property row carries its value',
         frame.rows[indexOfRow(frame, 'kettle')] === 'kettle\tcold');
}

function testPropertyOpensOverlay() {
  setUp();
  session.listBackends();
  session.activate(0);
  var frame = lastFrame();
  reset();
  session.activate(indexOfRow(frame, 'kettle'));

  var overlay = lastFrame();
  assert('a property opens the reading window', overlay.overlay === 3);
  assert('the overlay is headed by the key', overlay.heading === 'kettle');
  assert('the overlay body is the value', overlay.prompt === 'cold');
  /* The document underneath is unchanged: the overlay is on top of it, not
   * instead of it, so dismissing it needs no round trip. */
  assert('the document is still underneath',
         overlay.rows.length === frame.rows.length);
  assert('opening a property asks the server nothing', requested.length === 0);
}

function testFollowLinkAndBack() {
  setUp();
  session.listBackends();
  session.activate(0);
  var root = lastFrame();
  reset();

  session.activate(indexOfRow(root, 'shelves'));
  assert('a link is fetched by the href the server gave',
         requested[0] === 'GET ' + BASE + 'shelves');
  assert('the fetched document is shown', lastFrame().title === 'Shelves');

  reset();
  session.back();
  assert('back returns to the previous document',
         lastFrame().title === 'The pantry');
  assert('back asks the server nothing', requested.length === 0);

  reset();
  session.back();
  assert('back at the root returns to the picker',
         lastFrame().kinds === 'bb');
}

function testEmbeddedEntity() {
  setUp();
  session.listBackends();
  session.activate(0);
  var root = lastFrame();
  reset();

  session.activate(indexOfRow(root, 'Top shelf'));
  /* It arrived inside the document we already have. Fetching it again would
   * be asking a question we already know the answer to -- and could get a
   * different one. */
  assert('an embedded entity is opened without a request',
         requested.length === 0);
  assert('the embedded entity is shown',
         lastFrame().title === 'Top shelf');
  assert('the embedded entity renders its properties',
         indexOfRow(lastFrame(), 'jars') >= 0);
}

function testRefresh() {
  setUp();
  session.listBackends();
  session.activate(0);
  reset();

  session.refresh();
  assert('refresh re-fetches the current document',
         requested[0] === 'GET ' + BASE);
  assert('refresh does not deepen the stack',
         lastFrame().title === 'The pantry');

  /* An embedded document has no address of its own. */
  session.activate(indexOfRow(lastFrame(), 'Top shelf'));
  reset();
  session.refresh();
  assert('an embedded document cannot be re-fetched', requested.length === 0);
  assert('an embedded document is re-rendered instead',
         lastFrame().title === 'Top shelf');
}

function testFailureKeepsTheDocument() {
  setUp();
  session.listBackends();
  session.activate(0);
  var root = lastFrame();

  /* The failure the whole design exists to get right: the phone could not ask,
   * which says nothing about the state of the thing it would have asked about. */
  routes = {};
  reset();
  session.refresh();

  var frame = lastFrame();
  assert('a failed refresh keeps the document on screen',
         labels(frame).join(',') === labels(root).join(','));
  assert('a failed refresh says so in the banner', frame.message === 'Error');
  assert('the reason is readable in full',
         frame.overlay === 3 && frame.prompt === 'no such thing here');
}

function testUnreachableIsNotAnError() {
  setUp();
  session.listBackends();
  session.activate(0);

  /* status 0: the request never arrived anywhere. */
  FakeXHR.prototype.send = function () {
    requested.push(this.method + ' ' + this.url);
    this.status = 0;
    this.responseText = '';
    this.readyState = 4;
    this.onreadystatechange();
  };
  reset();
  session.refresh();

  var frame = lastFrame();
  assert('unreachable is its own state, not error', frame.state === 3);
  assert('unreachable says which host', /no answer from/.test(frame.prompt));
  FakeXHR.prototype.send = respondFromRoutes;
}

function testSwitchingBackendsResetsTheStack() {
  setUp();
  session.listBackends();
  session.activate(0);
  session.activate(indexOfRow(lastFrame(), 'shelves'));
  reset();

  session.listBackends();
  session.activate(1);
  reset();
  session.back();
  /* Not back into the first backend's documents: showing one server's state
   * under another server's name is the mistake this prevents. */
  assert('switching backends discards the old stack',
         lastFrame().kinds === 'bb');
}

/* --- actions -------------------------------------------------------------
 *
 * These are the tests where a bug means an unwanted request reaching a real
 * server, so they check what was sent as well as what was shown.
 */

/* openRoot leaves the root document on screen and the recorders empty, and
 * returns the frame as it was before the reset. */
function openRoot() {
  setUp();
  session.listBackends();
  session.activate(0);
  var frame = lastFrame();
  reset();
  return frame;
}

/* Nothing is sent on the press. On a four-button device the row that opens a
 * property and the row that changes the world must not act the same. */
function testUnsafeActionAsksFirst() {
  var root = openRoot();
  session.activate(indexOfRow(root, 'Brew a pot of tea'));

  var frame = lastFrame();
  assert('an unsafe action asks before acting', requested.length === 0);
  assert('the question is a confirmation, not a reading', frame.overlay === 1);
  assert('the question is headed by the server\'s wording',
         frame.heading === 'Brew a pot of tea');
  assert('the document is still underneath',
         frame.rows.length === root.rows.length);
}

/* Siren allows a GET action, and a read is not a change. */
function testSafeActionGoesStraightThrough() {
  var root = openRoot();
  session.activate(indexOfRow(root, 'Look inside'));
  assert('a safe action is not gated',
         requested[0] === 'GET ' + BASE + 'peek');
}

function testDeclining() {
  var root = openRoot();
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(false);

  assert('declining sends nothing', requested.length === 0);
  assert('declining clears the question', lastFrame().overlay === 0);
  assert('declining leaves the document in place',
         lastFrame().title === 'The pantry');
}

function testConfirmingInvokesAndRefetches() {
  var root = openRoot();
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(true);

  assert('confirming posts to the href the server gave',
         requested[0] === 'POST ' + BASE + 'brew');
  /* The contract's rule: never carry a document across an action. The only
   * trustworthy account of the result is the server's next answer. */
  assert('the document is re-fetched afterwards',
         requested[1] === 'GET ' + BASE);
  var frame = lastFrame();
  assert('the outcome survives the re-fetch', frame.message === 'done');
  assert('the response body is readable',
         frame.overlay === 3 && /id: 7/.test(frame.prompt));
  assert('the re-fetched document is what is shown',
         frame.title === 'The pantry');
}

/* A required checkbox IS the confirmation, so the sentence the server wrote
 * for it is the sentence to show -- and the answer is what fills the field. */
function testRequiredCheckbox() {
  var root = openRoot();
  session.activate(indexOfRow(root, 'Let the kettle cool'));
  assert('the checkbox title is the question asked',
         lastFrame().prompt === 'The kettle is still hot. Cool it anyway?');

  reset();
  session.answer(true);
  assert('confirming fills the checkbox', sentBodies[0] === 'confirm=true');
}

/* 409 means the state we acted on was stale. The remedy is to look again;
 * repeating the request the server just judged wrong is not. */
function testConflictRefetchesAndDoesNotRetry() {
  var root = openRoot();
  routes['POST ' + BASE + 'brew'] = { status: 409,
    body: { properties: { message: 'a brew is already running' } } };
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(true);

  var posts = 0;
  for (var i = 0; i < requested.length; i++) {
    if (requested[i].indexOf('POST') === 0) { posts++; }
  }
  assert('a 409 is not retried', posts === 1);
  assert('a 409 re-fetches instead', requested[1] === 'GET ' + BASE);
  var frame = lastFrame();
  assert('the conflict is reported', frame.message === 'Conflict');
  assert('the server explains it',
         frame.prompt === 'a brew is already running');
}

/* An auth failure says nothing new about the document, and re-fetching would
 * fail the same way. */
function testAuthFailureDoesNotRefetch() {
  var root = openRoot();
  routes['POST ' + BASE + 'brew'] = { status: 401,
    body: { properties: { message: 'API key rejected' } } };
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(true);

  assert('an auth failure does not re-fetch', requested.length === 1);
  assert('the auth failure is reported', lastFrame().message === 'Auth');
  assert('the document stays on screen', lastFrame().title === 'The pantry');
}

/* The server withdrew the action between rendering the row and pressing it.
 * That is a real answer -- it cannot be done now -- not a reason to guess. */
function testWithdrawnAction() {
  var root = openRoot();
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  /* The confirmation is on screen; now the document changes underneath it. */
  session.back();
  reset();
  session.answer(true);
  assert('answering a question that no longer applies sends nothing',
         requested.length === 0);
}

/* A required field with no default is asked for, never invented. */
function labelAction(fields) {
  setUp();
  routes[BASE] = { body: {
    class: ['pantry'], title: 'The pantry',
    links: [{ rel: ['self'], href: '/' }],
    actions: [{ name: 'label', title: 'Label a jar', method: 'POST',
                href: '/label', fields: fields }]
  } };
  routes['POST ' + BASE + 'label'] = { body: { properties: { state: 'done' } } };
  session.listBackends();
  session.activate(0);
  var frame = lastFrame();
  session.activate(indexOfRow(frame, 'Label a jar'));
  reset();
  session.answer(true);
}

function testRequiredFieldIsAskedFor() {
  labelAction([{ name: 'text', type: 'text', required: true,
                 title: 'What should the jar say?' }]);
  assert('nothing is sent while a value is missing', requested.length === 0);
  assert('the value is asked for out loud', lastFrame().overlay === 2);
  assert('the question uses the server\'s wording',
         lastFrame().heading === 'What should the jar say?');

  reset();
  session.answer(true, 'plum jam');
  assert('what was said is what is sent', sentBodies[0] === 'text=plum+jam');
}

function testNothingHeardSendsNothing() {
  labelAction([{ name: 'text', type: 'text', required: true }]);
  reset();
  /* Confirmed, but with no words: an empty value is not an answer. */
  session.answer(true, '');
  assert('an empty transcription sends nothing', requested.length === 0);
  assert('and says so', /Nothing was heard/.test(lastFrame().prompt));
}

function testDefaultsAreUsedWithoutAsking() {
  labelAction([{ name: 'text', type: 'text', required: true, value: 'jam' }]);
  assert('a server-supplied default is used as-is',
         sentBodies[0] === 'text=jam');
}

function testSeveralMissingFieldsAreRefused() {
  labelAction([{ name: 'text', type: 'text', required: true },
               { name: 'colour', type: 'text', required: true }]);
  assert('more than one missing value is refused, not dictated',
         requested.length === 0);
  assert('and the refusal explains itself',
         /more than/.test(lastFrame().prompt));
}

/* --- live mode -----------------------------------------------------------
 *
 * A job that outlives its request. The failure these guard against is a client
 * that reports "done" while the work is still running -- which is exactly what
 * happens if a poll landing on a machine that never saw the job is read as an
 * answer about it.
 */

var JOB = { class: ['kettle-job'], title: 'Kettle job',
            properties: { state: 'running', id: 7, step: 'heating the water',
                          staleAfterSeconds: 120 },
            links: [{ rel: ['self'], href: '/job' }] };

function jobBody(overrides) {
  var props = {};
  for (var key in JOB.properties) {
    if (Object.prototype.hasOwnProperty.call(JOB.properties, key)) {
      props[key] = JOB.properties[key];
    }
  }
  for (var over in overrides) {
    if (Object.prototype.hasOwnProperty.call(overrides, over)) {
      props[over] = overrides[over];
    }
  }
  return { class: ['kettle-job'], properties: props,
           links: [{ rel: ['self'], href: '/job' }] };
}

/* startBrew leaves a 202'd job being watched. */
function startBrew() {
  var root = openRoot();
  routes['POST ' + BASE + 'brew'] = { status: 202, body: jobBody({}) };
  routes[BASE + 'job'] = { body: jobBody({}) };
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(true);
}

function testLiveModeStartsOn202() {
  startBrew();
  assert('a 202 does not re-fetch and call it done',
         requested.length === 1 && requested[0].indexOf('POST') === 0);
  assert('the frame says it is live', lastFrame().atRoot === 0 &&
         sent[sent.length - 1][MESSAGE_KEYS.LIVE] === 1);
}

/* The poll target comes from matching the returned entity's class against the
 * origin document's link rels -- a hypermedia idiom, not a known path. */
function testPollTargetIsRelClassMatch() {
  startBrew();
  reset();
  tick(10000);
  assert('the job link is polled, not the origin',
         requested[0] === 'GET ' + BASE + 'job');
}

function testProgressIsReportedInTheServersWords() {
  startBrew();
  routes[BASE + 'job'] = { body: jobBody({ step: 'steeping' }) };
  reset();
  tick(10000);
  assert('the step is shown as the server worded it',
         lastFrame().message === 'steeping');
  assert('it is still live',
         sent[sent.length - 1][MESSAGE_KEYS.LIVE] === 1);
}

function testWatchingEndsAndRefetches() {
  startBrew();
  routes[BASE + 'job'] = { body: jobBody({ state: 'done', step: '' }) };
  reset();
  tick(10000);

  assert('the finished job is the last poll',
         requested[0] === 'GET ' + BASE + 'job');
  /* The job stopping is not the point -- the document it changed is. */
  assert('the origin document is re-fetched', requested[1] === 'GET ' + BASE);
  assert('the outcome is reported', lastFrame().message === 'done');
  assert('it is no longer live',
         sent[sent.length - 1][MESSAGE_KEYS.LIVE] === 0);
}

/* Load balancing means a poll can reach a machine that never saw this job.
 * "I do not have it" is not "it finished". */
function testPollAboutAnotherJobIsIgnored() {
  startBrew();
  routes[BASE + 'job'] = { body: jobBody({ id: 99, state: 'done' }) };
  reset();
  tick(10000);
  assert('an answer about another job does not end the watch',
         requested.length === 1);
  assert('and nothing claims it finished', lastFrame() === undefined);

  routes[BASE + 'job'] = { body: jobBody({ state: 'done' }) };
  tick(10000);
  assert('the right answer still ends it', lastFrame().message === 'done');
}

function testPollWithNoJobIsIgnored() {
  startBrew();
  routes[BASE + 'job'] = { body: jobBody({ state: 'none', id: 0 }) };
  reset();
  tick(10000);
  assert('a state of none does not end the watch', lastFrame() === undefined);
}

/* A failed poll is news about the network, not about the job. */
function testFailedPollKeepsWatching() {
  startBrew();
  delete routes[BASE + 'job'];
  routes[BASE + 'job'] = null;
  var saved = FakeXHR.prototype.send;
  FakeXHR.prototype.send = function () {
    requested.push(this.method + ' ' + this.url);
    this.status = 0;
    this.responseText = '';
    this.readyState = 4;
    this.onreadystatechange();
  };
  reset();
  tick(10000);
  assert('a failed poll does not end the watch', lastFrame() === undefined);
  FakeXHR.prototype.send = saved;
  routes[BASE + 'job'] = { body: jobBody({ state: 'done' }) };
  tick(10000);
  assert('watching resumes when the network does',
         lastFrame().message === 'done');
}

/* The deadline is the server's own budget, not a number in this app. */
function testDeadlineComesFromTheServer() {
  var root = openRoot();
  routes['POST ' + BASE + 'brew'] = { status: 202,
    body: jobBody({ staleAfterSeconds: 1 }) };
  routes[BASE + 'job'] = { body: jobBody({ staleAfterSeconds: 1 }) };
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(true);

  /* 1s of budget plus the 60s buffer: the poll at 10s is inside it, the one
   * after 70s is not. */
  tick(10000);
  assert('polling continues inside the budget',
         lastFrame().message === 'heating the water');
  tick(70000);
  assert('it gives up when the budget runs out',
         lastFrame().message === 'Gave up');
  /* Giving up is a failure to keep watching, not a claim the job failed. */
  assert('and says the job may still be running',
         /may still be working/.test(lastFrame().prompt));
}

function testNavigatingAwayStopsWatching() {
  startBrew();
  reset();
  session.back();
  tick(30000);
  var polls = 0;
  for (var i = 0; i < requested.length; i++) {
    if (requested[i].indexOf('job') > 0) { polls++; }
  }
  assert('leaving the screen stops the watch', polls === 0);
}

/* --- the bounded retry ---------------------------------------------------
 *
 * The one case where repeating a request is right: the user ticked a required
 * checkbox, and the server judged the same request twice on budgets that
 * changed in between.
 */

function testConfirmedActionRetriesOnce() {
  var root = openRoot();
  var attempts = 0;
  routes['POST ' + BASE + 'cool'] = { status: 409,
    body: { properties: { message: 'needs confirmation' } } };
  var saved = FakeXHR.prototype.send;
  FakeXHR.prototype.send = function (body) {
    if (this.method === 'POST') {
      attempts++;
      if (attempts === 2) {
        /* The retry is accepted, as the contract says it may be. */
        routes['POST ' + BASE + 'cool'] = { body: { properties: { state: 'done' } } };
      }
    }
    saved.call(this, body);
  };

  session.activate(indexOfRow(root, 'Let the kettle cool'));
  reset();
  session.answer(true);
  FakeXHR.prototype.send = saved;

  assert('a confirmed action is retried exactly once', attempts === 2);
  assert('both attempts carried the confirmation',
         sentBodies[0] === 'confirm=true' && sentBodies[1] === 'confirm=true');
  assert('the retry succeeding is what is reported',
         lastFrame().message === 'done');
}

function testUnconfirmedActionIsNotRetried() {
  var root = openRoot();
  routes['POST ' + BASE + 'brew'] = { status: 409,
    body: { properties: { message: 'a brew is already running' } } };
  session.activate(indexOfRow(root, 'Brew a pot of tea'));
  reset();
  session.answer(true);

  var posts = 0;
  for (var i = 0; i < requested.length; i++) {
    if (requested[i].indexOf('POST') === 0) { posts++; }
  }
  /* No required checkbox means nothing was confirmed, so there is nothing to
   * re-send -- and inventing one would be doing something nobody asked for. */
  assert('an action with nothing confirmed is never retried', posts === 1);
}

function testRetryIsNotRepeated() {
  var root = openRoot();
  routes['POST ' + BASE + 'cool'] = { status: 409,
    body: { properties: { message: 'still no' } } };
  session.activate(indexOfRow(root, 'Let the kettle cool'));
  reset();
  session.answer(true);

  var posts = 0;
  for (var i = 0; i < requested.length; i++) {
    if (requested[i].indexOf('POST') === 0) { posts++; }
  }
  assert('a retry that also conflicts is not retried again', posts === 2);
  assert('and the conflict is reported', lastFrame().message === 'Conflict');
}

/* --- idle refresh -------------------------------------------------------- */

function testIdleRefresh() {
  openRoot();
  tick(60000);
  assert('the visible document is re-read when idle',
         requested[requested.length - 1] === 'GET ' + BASE);

  /* A refresh nobody asked for must not take the screen away from someone
   * who is reading it. */
  var root = openRoot();
  session.activate(indexOfRow(root, 'kettle'));
  reset();
  tick(60000);
  assert('an open overlay suppresses it', requested.length === 0);

  /* Found in live use: the watch dismisses a reading overlay by itself, and
   * without a word from it the suppression latched on and the background
   * refresh never resumed. */
  var again = openRoot();
  session.activate(indexOfRow(again, 'kettle'));
  session.setSeq(99);
  session.dismissed();
  reset();
  tick(60000);
  assert('dismissing the overlay lets it resume',
         requested[requested.length - 1] === 'GET ' + BASE);

  /* And a quiet failure sets the banner rather than throwing an overlay over
   * whatever is on screen. */
  openRoot();
  routes = {};
  tick(60000);
  assert('a failed idle refresh does not open an overlay',
         lastFrame().overlay === 0);
  assert('but it does say so', lastFrame().message === 'Error');
}

/* Only the picker is the root, and only there does BACK leave the app. Getting
 * this wrong either traps the user inside RESTForge with no way out, or drops
 * them onto the watchface from the middle of a document. */
function testRootFlag() {
  setUp();
  session.listBackends();
  assert('the picker is the root', lastFrame().atRoot === 1);

  session.activate(0);
  assert('a document is not the root', lastFrame().atRoot === 0);

  session.activate(indexOfRow(lastFrame(), 'shelves'));
  assert('a deeper document is not the root', lastFrame().atRoot === 0);

  session.back();
  session.back();
  assert('back at the bottom returns to the root', lastFrame().atRoot === 1);
}

/* --- the quick menu ------------------------------------------------------
 *
 * Save the focused row, find it on the opening screen, press it. The property
 * being defended is that a shortcut skips the walking, not the deciding.
 */

var quick = require(path.join(__dirname, '..', 'src', 'pkjs', 'quick'));

function testSaveAndRunAQuickAction() {
  var root = openRoot();
  quick.save([]);

  session.saveQuick(indexOfRow(root, 'Brew a pot of tea'));
  assert('saving reports it', lastFrame().message === 'Saved');
  assert('saving asks the server nothing', requested.length === 0);

  reset();
  session.listBackends();
  var picker = lastFrame();
  /* Shortcuts lead the opening screen; backends follow. */
  assert('the shortcut is first on the opening screen',
         picker.kinds.indexOf('q') === 0);
  assert('labelled as the server worded it',
         labels(picker)[0] === 'Brew a pot of tea');

  reset();
  session.activate(0);
  /* The holder is re-read so the action is looked up by name in a current
   * document, rather than fired at a remembered href. */
  assert('running it re-reads the document that offers it',
         requested[0] === 'GET ' + BASE);
  assert('and it still asks before acting', lastFrame().overlay === 1);
  assert('the press alone sends nothing',
         requested.join(',').indexOf('POST') < 0);

  reset();
  session.answer(true);
  assert('confirming is what invokes it',
         requested[0] === 'POST ' + BASE + 'brew');
}

function testQuickDocument() {
  var root = openRoot();
  quick.save([]);
  session.saveQuick(indexOfRow(root, 'shelves'));

  reset();
  session.listBackends();
  session.activate(0);
  assert('a saved link is fetched directly',
         requested[0] === 'GET ' + BASE + 'shelves');
  assert('and shown', lastFrame().title === 'Shelves');
  /* Straight to the destination: nothing walked, so BACK returns to the
   * opening screen rather than into a history nobody visited. */
  reset();
  session.back();
  assert('back from a shortcut returns to the opening screen',
         lastFrame().kinds.indexOf('q') === 0);
}

/* A property opens a reading window; there is nowhere to return to. */
function testUnsaveableRow() {
  var root = openRoot();
  quick.save([]);
  session.saveQuick(indexOfRow(root, 'kettle'));
  assert('a property row is refused', quick.count() === 0);
  assert('and says so', /Cannot save/.test(lastFrame().message));
}

/* A shortcut whose backend was deleted explains itself rather than vanishing
 * or firing at a server that is no longer configured. */
function testShortcutToDeletedBackend() {
  var root = openRoot();
  quick.save([]);
  session.saveQuick(indexOfRow(root, 'shelves'));
  settings.save([{ name: 'other', baseUrl: 'http://elsewhere.example/',
                   secret: 'x' }]);

  session.listBackends();
  reset();
  session.activate(0);
  assert('it does not reach for the old server', requested.length === 0);
  assert('it says the backend is gone',
         /no longer configured/.test(lastFrame().prompt));
}

function testSequenceIsEchoed() {
  setUp();
  session.setSeq(42);
  session.listBackends();
  assert('the frame echoes the command it answers', lastFrame().seq === 42);
}

testPicker();
testOpenAndRender();
testPropertyOpensOverlay();
testFollowLinkAndBack();
testEmbeddedEntity();
testRefresh();
testFailureKeepsTheDocument();
testUnreachableIsNotAnError();
testSwitchingBackendsResetsTheStack();
testUnsafeActionAsksFirst();
testSafeActionGoesStraightThrough();
testDeclining();
testConfirmingInvokesAndRefetches();
testRequiredCheckbox();
testConflictRefetchesAndDoesNotRetry();
testAuthFailureDoesNotRefetch();
testWithdrawnAction();
testRequiredFieldIsAskedFor();
testNothingHeardSendsNothing();
testDefaultsAreUsedWithoutAsking();
testSeveralMissingFieldsAreRefused();
testLiveModeStartsOn202();
testPollTargetIsRelClassMatch();
testProgressIsReportedInTheServersWords();
testWatchingEndsAndRefetches();
testPollAboutAnotherJobIsIgnored();
testPollWithNoJobIsIgnored();
testFailedPollKeepsWatching();
testDeadlineComesFromTheServer();
testNavigatingAwayStopsWatching();
testConfirmedActionRetriesOnce();
testUnconfirmedActionIsNotRetried();
testRetryIsNotRepeated();
testIdleRefresh();
testRootFlag();
testSaveAndRunAQuickAction();
testQuickDocument();
testUnsaveableRow();
testShortcutToDeletedBackend();
testSequenceIsEchoed();

if (failures) {
  realLog(failures + ' failure(s)');
  process.exit(1);
}
realLog('session: all checks passed');
